RakshaDjangoLearning/firstProject/firstProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
]

RakshaDjangoLearning/firstProject/main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('products/', views.products, name='products'),
    path(r'getToDoListId/<int:id>', views.index1, name='index1'),
    path("getToDoListName/<int:id>", views.index2, name='index2'),
    path("create/", views.create, name='create'),
    path("createToDolist/", views.createToDolist, name='createToDolist'),
]

RakshaDjangoLearning/firstProject/main/models.py
from django.db import models

# Create your models here.


class ToDoList(models.Model):
    name = models.CharField(max_length=500)

    def __str__(self):
        return self.name


class Items(models.Model):
    todolist = models.ForeignKey(ToDoList, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    complete = models.BooleanField()

    def __str__(self):
        return self.text

RakshaDjangoLearning/firstProject/main/forms.py
from django import forms


class CreateNewList(forms.Form):
    name = forms.CharField(label="Name", max_length=200)
    check = forms.BooleanField()

RakshaDjangoLearning/firstProject/main/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect

from .forms import CreateNewList
from .models import ToDoList, Items


def home(response):
    return render(response, "main/home.html", {})


def createToDolist(request):
    form = CreateNewList(request.POST)
    # print(form.errors)
    # form.add_error('name', "max length not")
    # print(type(form.errors))

    if form.is_valid():
        n = form.cleaned_data["name"]
        t = ToDoList(name=n)
        t.save()
        return HttpResponseRedirect('/getToDoListId/%i' % t.id)
    else:
        return render(request, "main/create.html", {"form": form})


def create(response):
    if response.method == "POST":
       form = CreateNewList(response.POST)

       if form.is_valid():
           n = form.cleaned_data["name"]
           t = ToDoList(name=n)
           t.save()

           return HttpResponseRedirect("/getToDoListId/%i" %t.id)

    else:
        form = CreateNewList()
    return render(response, "main/create.html", {"form": form})


def products(request):
    return HttpResponse("Products page")


def index1(response, id):
    ls = ToDoList.objects.get(id=id)
    print(ls)
    return render(response, "main/list.html", {"ls": ls})


def index2(request, id):
    ls1 = ToDoList.objects.get(id=id)
    return HttpResponse("<h1>%s</h1>" %ls1.name)





# Create your views here.

RakshaDjangoLearning/firstProject/main/templates/main/base.html
<html>
<head>

    <title>
        {% block title %} AKN Fashions {% endblock %}
    </title>

</head>

<body>
    <div id ="content", name="content">
    {% block content %}
    {% endblock %}
    </div>


</body>

</html>

RakshaDjangoLearning/firstProject/main/templates/main/create.html
{% extends 'main/base.html' %}

{% block title %} Create New List {% endblock %}

{% block content%}
Create New
<form method="post" action="/create/">
  {% csrf_token%}
  {{form.as_p}}
  <button type="submit" >create new</button>
</form>
{% endblock %}

RakshaDjangoLearning/firstProject/main/templates/main/home.html
{% extends 'main/base.html' %}

{% block title%}
<h1>Home</h1>
{% endblock %}

{% block content%}
<h1>Home Page</h1>
{% endblock%}

RakshaDjangoLearning/firstProject/main/templates/main/list.html
{% extends "main/base.html" %}

{% block title %}<h1>View List</h1>{% endblock %}

{% block content%}
   <h1>{{ls.name}}</h1>
   <ul>
       {% for item in ls.items_set.all %}
         {% if item.complete == False %}
             <li>{{item.text}} --Not complete</li>
         {% endif %}
       {% endfor %}
   </ul>
{% endblock %}